denoiser:
  target: mld.models.architectures.mld_denoiser.MldDenoiser
  params:
    text_encoded_dim: 256
    ff_size: 128 #128 #1024 #
    num_layers: 5 #s1:9, s2:5
    num_heads: 1 #s1:4, s2:1
    dropout: 0.1
    normalize_before: False
    activation: 'gelu'
    flip_sin_to_cos: True
    return_intermediate_dec: False
    position_embedding: 'learned'
    arch: trans_enc
    freq_shift: 0
    condition: ${model.condition}
    latent_dim: ${model.latent_dim}
    guidance_scale: ${model.guidance_scale}
    guidance_uncondp: ${model.guidance_uncondp}
    nfeats: ${model.nfeats}
    nclasses: ${DATASET.NCLASSES}
    ablation: ${TRAIN.ABLATION}
