#### config params for stage 1: prohmr-scene ###
SMPL:
  MEAN_PARAMS: data/smpl_mean_params.npz
TRAIN:
  LR: 1e-4
  WEIGHT_DECAY: 1e-4
  NUM_TRAIN_SAMPLES: 2
  NUM_TEST_SAMPLES: 4
  POSE_2D_NOISE_RATIO: 0.01
  SMPL_PARAM_NOISE_RATIO: 0.005
LOSS_WEIGHTS:
  V2V_EXP: 0.0
  V2V_MODE: 0.5
  # for pelvis-aligned 3d joint loss
  KEYPOINTS_3D_EXP: 0.0
  KEYPOINTS_3D_MODE: 0.05
  # for global 3d joint loss
  KEYPOINTS_3D_FULL_EXP: 0.0
  KEYPOINTS_3D_FULL_MODE: 0.02
  # for cropped image 2d joint loss
  KEYPOINTS_2D_EXP: 0.001
  KEYPOINTS_2D_MODE: 0.01
  # for full image 2d joint loss
  KEYPOINTS_2D_FULL_EXP: 0.001
  KEYPOINTS_2D_FULL_MODE: 0.01
  # smpl params loss
  GLOBAL_ORIENT_EXP: 0.000
  GLOBAL_ORIENT_MODE: 0.001  #
  BODY_POSE_EXP: 0.0
  BODY_POSE_MODE: 0.001
  ORTHOGONAL: 0.1
  BETAS_EXP: 0.0
  BETAS_MODE: 0.0005
  TRANSL: 0.1
  NLL: 0.001
  ADVERSARIAL: 0.0005
MODEL:
  IMAGE_SIZE: 224
  IMAGE_MEAN: [0.485, 0.456, 0.406]
  IMAGE_STD: [0.229, 0.224, 0.225]
  BACKBONE:
    TYPE: resnet
    NUM_LAYERS: 50
    OUT_CHANNELS: 2048
  FLOW:
    DIM: 144
    NUM_LAYERS: 4
    CONTEXT_FEATURES: 2048
    LAYER_HIDDEN_FEATURES: 1024
    LAYER_DEPTH: 2
  FC_HEAD:
    NUM_FEATURES: 1024
EXTRA:
  FOCAL_LENGTH: 5000
CAM:
  FX_NORM_COEFF: 1500
  FY_NORM_COEFF: 1500
  CX_NORM_COEFF: 960
  CY_NORM_COEFF: 540

